name: 🐞 Bug Report
description: File a bug report
title: "Bug: "
labels: ["🛠 goal: fix", "🚦status: awaiting triage", "💻 aspect: code"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Add descriptions
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to page X
        2. Click here
        3. Click there
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What was the expected result?
      placeholder: I expected this to happen
  - type: textarea
    id: screenshots
    attributes:
      label: Put here any screenshots or videos (optional)
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Brave
        - Other
  - type: checkboxes
    id: terms
    attributes:
      label: "Record"
      options:
        - label: I have checked the existing [issues](https://github.com/serene-server/ketone/issues)
          required: true

        - label: I have read the [Contributing Guidelines](https://github.com/serene-server/ketone/blob/main/CONTRIBUTING.md)
          required: true

        - label: I agree to follow this project's [Code of Conduct](https://github.com/serene-server/ketone/blob/main/CODE_OF_CONDUCT.md)
          required: true

        - label: I want to work on this issue
