blank_issues_enabled: true
contact_links:
  - name: Questions
    url: mailto:mogalapallinitin@gmail.com
    about: You can mail regarding the queries.
  - name: Login does not work
    url: https://github.com/serene-server/ketone/blob/main/CONTRIBUTING.md
    about: Before opening a new issue, please make sure to read CONTRIBUTING.md
